### ISSUE TITLE
dual image list Error

### ISSUE THREAD

**Issue by jslauzon** [nedhorning/PhotoMonitoringPlugin#9]
Hi Ned,
Whenever I try to create a dual image list, I get this error:
(Fiji Is Just) ImageJ 2.0.0-rc-15/1.49k; Java 1.6.0_24 [64-bit]; Windows NT (unknown) 6.2; 25MB of 12195MB (<1%)
 
java.lang.NullPointerException
	at FilePairList.getExifTime(FilePairList.java:95)
	at FilePairList.<init>(FilePairList.java:26)
	at List_Files.run(List_Files.java:96)
	at ij.IJ.runUserPlugIn(IJ.java:202)
	at ij.IJ.runPlugIn(IJ.java:166)
	at ij.Executer.runCommand(Executer.java:131)
	at ij.Executer.run(Executer.java:64)
	at java.lang.Thread.run(Thread.java:662)

any idea what the issue might be?
Thanks
JS

**Comment by nedhorning** [comment]
Hi JS -

Are you using the images as they came out of the camera or have they 
been processed in some way. I looks like the program is not finding the 
dateTime tag that should be in the image metadata created by the camera. 
If you saved the file from another program that tag could be deleted.

If that doesn't seem to be the problem would you be be able to send me 
some of the image pairs you are trying to process and I'll see if I can 
track down the problem.

Ned

**Comment by jslauzon** [comment]
Image came straight out of the camera (Parrot Sequoia).
Here's a link to the files
https://www.dropbox.com/sh/yg49lrwqn1ajizn/AAAh3_5IUk1uWIIdTbTsllDra?dl=0

Thanks for your help!

**Comment by nedhorning** [comment]
Thanks - It's interesting but for some reason the library 
(metadata-extractor) I'm using can't read the metadata in those images. 
I am able to read it using exiftool but not when I use the image viewer 
software I use. I'm guessing that reading TIFF tags is not supported. I 
am using an outdated version of the metadata-extractor library and 
probably should update it but some of the classes have changed so it's a 
few hours of work if I'm lucky and just haven't found the time to do it 
- mostly since it hasn't been a problem. I can try to look at it but I'm 
swamped with other things right now so have no idea when I'll be able to 
get to it. I also have no idea if updating the library will fix the 
problem. Do you happen to know Java?

Sorry I can't be more helpful.

Ned

**Comment by jslauzon** [comment]
No Java here... 
Your plugin was much more convivial, but I can calculate NDVI by using an image registration plugin and then use the image calculator. So, don't worry about it, especially if I'm the only one with this problem...
Thanks for your help
JS

**Comment by nedhorning** [comment]
Another solution is to create the image pair file by hand if you know 
which images get paired with the other. I often do that if I only have 
one or two image pairs to work with. I attached an example file.

Ned

On 01/24/2017 02:01 PM, jslauzon wrote:
>
> No Java here...
> Your plugin was much more convivial, but I can calculate NDVI by using 
> an image registration plugin and then use the image calculator. So, 
> don't worry about it, especially if I'm the only one with this problem...
> Thanks for your help
> JS
>
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub 
> <https://na01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnedhorning%2FPhotoMonitoringPlugin%2Fissues%2F9%23issuecomment-274901777&data=01%7C01%7Chorning%40amnh.org%7C9ca790ccf1f1400f9fbe08d4448b7689%7Cbe0003e8c6b9496883aeb34586974b76%7C0&sdata=XNsoa1SdcAOf2Tfgd%2BNI2zZ8hThhn8qQRi%2F9covcApI%3D&reserved=0>, 
> or mute the thread 
> <https://na01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FABt-kkton3wTCLNA3Z0oELD55a04CQdyks5rVkqfgaJpZM4Lsky_&data=01%7C01%7Chorning%40amnh.org%7C9ca790ccf1f1400f9fbe08d4448b7689%7Cbe0003e8c6b9496883aeb34586974b76%7C0&sdata=08iP2%2F%2BSSxVYw5j%2BTWgbOr1IjsSyLv85666SgM5OZvo%3D&reserved=0>.
>


/RiptonTestIR/IMG_3947.JPG, /RiptonTestVis/IMG_2980.JPG
/RiptonTestIR/IMG_3948.JPG, /RiptonTestVis/IMG_2981.JPG
/RiptonTestIR/IMG_3949.JPG, /RiptonTestVis/IMG_2982.JPG

**Comment by jslauzon** [comment]
I get an "Error writing log file"
and all it says is : 1
maybe I'm not setting the path to the file correctly. I start with C:/...

**Comment by nedhorning** [comment]
That can happen if there is one or more blank lines after the last line 
of text in the paired image file. To prevent this from happening be sure 
to remove all white space after the last line of text in the paired 
image file.

**Comment by jslauzon** [comment]
That doesn't seem to be the issue...
here's my file...
[try.txt](https://github.com/nedhorning/PhotoMonitoringPlugin/files/727747/try.txt)

**Comment by nedhorning** [comment]
Does it work if you change the forward slash to a backward slash?

**Comment by jslauzon** [comment]
No, I tried it both ways

**Comment by nedhorning** [comment]
I'm stumped. I have some meetings for the rest of the day but will try 
to process the two images you sent. Sorry for the trouble

Ned

**Comment by nedhorning** [comment]
I did a quick test and it looks like it's choking on the TIFF image. 
ImageJ reads these TIFF images somewhat different from a JPEG. That can 
almost certainly be fixed but won't be able to do it soon. Again, sorry 
this isn't working out for you.

Ned
